name: build release (win + linux)

on:
  push:
    tags: [ '*.*.*' ]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  SCRIPT_NAME: main
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    name: build ${{ matrix.platform }} (${{ matrix.nuitka_mode }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows
            nuitka_mode: standalone
          - os: windows-latest
            platform: windows
            nuitka_mode: onefile
          - os: ubuntu-latest
            platform: linux
            nuitka_mode: standalone

    steps:
      - name: Set NUITKA_OUTPUT (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: echo "NUITKA_OUTPUT=${{ env.REPO_NAME }}.exe" >> "$GITHUB_ENV"
      - name: Set NUITKA_OUTPUT (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: echo "NUITKA_OUTPUT=${{ env.REPO_NAME }}" >> "$GITHUB_ENV"
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: 'pyproject.toml'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: '0.9.26'
      - name: Install deps
        shell: bash
        run: |
          uv export --output-file requirements.lock.txt
          uv pip install --system -r requirements.lock.txt
      - name: Build UI (Windows)
        if: runner.os == 'Windows'
        run: ui/make.bat
      - name: Build UI (Linux)
        if: runner.os == 'Linux'
        working-directory: ui
        run: make
      - name: Nuitka Build
        uses: Nuitka/Nuitka-Action@v1.4
        with:
          script-name: ${{ env.SCRIPT_NAME }}.py
          msvc: latest
          mode: ${{ matrix.nuitka_mode }}
          output-file: ${{ env.NUITKA_OUTPUT }}
      - name: Add LICENSE (standalone)
        if: matrix.nuitka_mode == 'standalone'
        shell: bash
        run: cp LICENSE build/${{ env.SCRIPT_NAME }}.dist/
      - name: Create archive (standalone)
        if: matrix.nuitka_mode == 'standalone'
        uses: thedoctor0/zip-release@0.7.6
        with:
          filename: ${{ env.REPO_NAME }}-${{ env.VERSION }}-${{ matrix.platform }}.zip
          directory: build/${{ env.SCRIPT_NAME }}.dist/
          type: 7z
      - name: Rename onefile
        if: matrix.nuitka_mode == 'onefile'
        shell: bash
        run: mv build/${{ env.NUITKA_OUTPUT }} ${{ env.REPO_NAME }}-${{ env.VERSION }}-${{ matrix.platform }}.exe
      - name: Upload workflow artifact (standalone)
        if: matrix.nuitka_mode == 'standalone'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.REPO_NAME }}-${{ env.VERSION }}-${{ matrix.platform }}-${{ matrix.nuitka_mode }}
          path: build/${{ env.SCRIPT_NAME }}.dist/${{ env.REPO_NAME }}-${{ env.VERSION }}-${{ matrix.platform }}.zip
      - name: Upload workflow artifact (onefile)
        if: matrix.nuitka_mode == 'onefile'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.REPO_NAME }}-${{ env.VERSION }}-${{ matrix.platform }}-${{ matrix.nuitka_mode }}
          path: ${{ env.REPO_NAME }}-${{ env.VERSION }}-${{ matrix.platform }}.exe

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          path: dist
          merge-multiple: true

      - name: Create/Update GitHub Release and upload assets
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          artifacts: dist/*
          generateReleaseNotes: true
